startup_metrics:
  target: prod
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: startup-metrics-dashboard
      dataset: startup_finance
      threads: 4
      timeout_seconds: 300
      keyfile: "/Users/rakshiths/startup-dashboard/creds.json"

    prod:
      type: bigquery
      method: service-account
      project: startup-metrics-dashboard
      dataset: startup_finance
      threads: 4
      timeout_seconds: 300
      keyfile: "/Users/rakshiths/startup-dashboard/creds.json"

