# name: Run dbt

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#   schedule:
#     - cron: '0 5 * * *'  # Runs at 5 AM UTC every day

# jobs:
#   run-dbt:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install dbt-bigquery

#       - name: Run dbt
#         run: |
#           source venv/bin/activate
#           dbt deps
#           dbt build
#         env:
#           DBT_PROFILES_DIR: .dbt  # or specify where your profiles.yml lives

name: Run dbt

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Run dbt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/creds.json
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > /tmp/creds.json
          dbt deps
          dbt debug --target dev
          dbt build --target dev
